# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a46234984c26bdbea79f72abf08bab2a239db2702b6b9f46d3a48c44bda69b2124544085facc3a0d2a48895d3fcead65b8951a41296a7fe638b9752eff3223f

test:
  secret_key_base: 9430104302f65cb914f5ed5bfd1913a4880cc26f0ae6d91987e7849118ae96b6179280b0301699e76d9243785c43fee4121033038d9564af32e37c863360948f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
